shoppley.com/shoppley/apps/offer/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from offer.views import *

urlpatterns = patterns('',
  url(r'^$', offer_home, name="offer_home"),
	url(r'offers/$', customer_offer_home, name="customer_offer_home"),
	url(r'business-home/$', merchant_offer_home, name="merchant_offer_home"),
	url(r'offer/(?P<offer_id>\d+)/$', customer_offer, name="customer_offer"),
	url(r'sendme/(?P<offer_id>\d+)/$', customer_offer_sendme, name="customer_offer_sendme"),
	url(r'business-offer/(?P<offer_id>\d+)/$', merchant_offer, name="merchant_offer"),
	url(r'admin-start/(?P<merchant_id>\d+)/$', admin_start_offer, name="admin_start_offer"),
	url(r'search-merchant/$', search_merchant, name="search_merchant"),
	url(r'^start/$', start_offer, name="start_offer"),
	url(r'^test/$', test_offer, name="test_offer"),
	url(r'^start-offer/$', merchant_start_offer, name="merchant_start_offer"),	

	
)

shoppley.com/shoppley/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib import admin
admin.autodiscover()

from account.openid_consumer import PinaxConsumer
from blog.feeds import BlogFeedAll, BlogFeedUser
from bookmarks.feeds import BookmarkFeed
from microblogging.feeds import TweetFeedAll, TweetFeedUser, TweetFeedUserWithFriends

from shoppleyuser.forms import CustomerSignupForm,MerchantSignupForm

from shoppleyuser.models import Category
tweets_feed_dict = {"feed_dict": {
    'all': TweetFeedAll,
    'only': TweetFeedUser,
    'with_friends': TweetFeedUserWithFriends,
}}

blogs_feed_dict = {"feed_dict": {
    'all': BlogFeedAll,
    'only': BlogFeedUser,
}}

bookmarks_feed_dict = {"feed_dict": { '': BookmarkFeed }}


if settings.ACCOUNT_OPEN_SIGNUP:
    signup_view = "account.views.signup"
else:
    signup_view = "signup_codes.views.signup"


urlpatterns = patterns('',

#    url(r'^$', direct_to_template, {
#        "template": "homepage.html", "extra_context": {"form": CustomerSignupForm},
#    }, name="home"),
#    url(r'^$', direct_to_template, {
#        "template": "front-page.html", "extra_context": {"form": CustomerSignupForm, "mform":MerchantSignupForm},
#    }, name="home"),
    url(r'^$', 'shoppleyuser.views.home', name="home"),
    url(r'^fb-fail', 'shoppleyuser.views.home_fb_fail', name="home_fb_fail"),
    url(r'^', include('common.urls')),
    url(r'^premium/', include('premium.urls')),
    
    #url(r'^comingsoon/$', direct_to_template, {
    #    "template": "comingsoon.html", "extra_context": {"form": CustomerBetaSubscribeForm, "categories":Category.objects.all()},
    #}, name="home"),

    url(r'^admin/invite_user/$', 'signup_codes.views.admin_invite_user', name="admin_invite_user"),
    url(r'^account/signup/$', signup_view, name="acct_signup"),
    url(r'^account/login/$', 'shoppleyuser.views.login', name="shoppleyuser_login"),
    url(r'^account/info/$', 'shoppleyuser.views.account_info',name="account_info"),
    url(r'^account/test/$', 'shoppleyuser.views.account_test', name="account_test"),
    (r'^about/', include('about.urls')),
    (r'^account/', include('account.urls')),
    (r'^openid/(.*)', PinaxConsumer()),
    (r'^bbauth/', include('bbauth.urls')),
    (r'^authsub/', include('authsub.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^blog/', include('blog.urls')),
    (r'^invitations/', include('friends_app.urls')),
    (r'^notices/', include('notification.urls')),
    (r'^messages/', include('messages.urls')),
    (r'^announcements/', include('announcements.urls')),
    (r'^tweets/', include('microblogging.urls')),
    (r'^tribes/', include('tribes.urls')),
    (r'^comments/', include('threadedcomments.urls')),
    (r'^robots.txt$', include('robots.urls')),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^bookmarks/', include('bookmarks.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^photos/', include('photos.urls')),
    (r'^avatar/', include('avatar.urls')),
    (r'^swaps/', include('swaps.urls')),
    (r'^flag/', include('flag.urls')),
    (r'^search/', include('haystack.urls')),
    (r'^locations/', include('locations.urls')),
    url(r'^social/', include('socialregistration.urls')),
	(r'^offer/', include('offer.urls')),
	(r'^shoppleyuser/', include('shoppleyuser.urls')),
	(r'^m/', include('mobile.urls')),
	(r'^buxfer/', include('buxfer.urls')),
	(r'^im/', include('instantmessage.urls')),
    
    (r'^feeds/tweets/(.*)/$', 'django.contrib.syndication.views.feed', tweets_feed_dict),
    (r'^feeds/posts/(.*)/$', 'django.contrib.syndication.views.feed', blogs_feed_dict),
    (r'^feeds/bookmarks/(.*)/?$', 'django.contrib.syndication.views.feed', bookmarks_feed_dict),
)

## @@@ for now, we'll use friends_app to glue this stuff together

from photos.models import Image

friends_photos_kwargs = {
    "template_name": "photos/friends_photos.html",
    "friends_objects_function": lambda users: Image.objects.filter(is_public=True, member__in=users),
}

from blog.models import Post

friends_blogs_kwargs = {
    "template_name": "blog/friends_posts.html",
    "friends_objects_function": lambda users: Post.objects.filter(author__in=users),
}

from microblogging.models import Tweet

friends_tweets_kwargs = {
    "template_name": "microblogging/friends_tweets.html",
    "friends_objects_function": lambda users: Tweet.objects.filter(sender_id__in=[user.id for user in users], sender_type__name='user'),
}

from bookmarks.models import Bookmark

friends_bookmarks_kwargs = {
    "template_name": "bookmarks/friends_bookmarks.html",
    "friends_objects_function": lambda users: Bookmark.objects.filter(saved_instances__user__in=users),
    "extra_context": {
        "user_bookmarks": lambda request: Bookmark.objects.filter(saved_instances__user=request.user),
    },
}

urlpatterns += patterns('',
    url('^photos/friends_photos/$', 'friends_app.views.friends_objects', kwargs=friends_photos_kwargs, name="friends_photos"),
    url('^blog/friends_blogs/$', 'friends_app.views.friends_objects', kwargs=friends_blogs_kwargs, name="friends_blogs"),
    url('^tweets/friends_tweets/$', 'friends_app.views.friends_objects', kwargs=friends_tweets_kwargs, name="friends_tweets"),
    url('^bookmarks/friends_bookmarks/$', 'friends_app.views.friends_objects', kwargs=friends_bookmarks_kwargs, name="friends_bookmarks"),
)

if settings.SERVE_MEDIA:
	urlpatterns += staticfiles_urlpatterns()

"""
if settings.SERVE_MEDIA:
    urlpatterns += patterns('',
        (r'^site_media/', include('staticfiles.urls')),
    )
"""

shoppley.com/shoppley/apps/offer/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.gis.geos import fromstr
from django.utils.translation import ugettext as _
from django.utils.translation import ungettext, string_concat

from shoppleyuser.utils import sms_notify, pretty_date, parse_phone_number
from shoppleyuser.models import Customer, Merchant, ShoppleyUser, CustomerPhone, MerchantPhone, Location
from offer.utils import gen_offer_code, gen_random_pw, gen_tracking_code, pretty_datetime, TxtTemplates
from sorl.thumbnail import ImageField
import logicaldelete.models

from datetime import datetime, timedelta

import random, string, time
#import logicaldelete.models.Model

SMS_DEBUG = settings.SMS_DEBUG

# Create your models here.

class Feature(models.Model):
	"""
		Featured location that users can see in their offer
		home page so that they may add to their preferred merchants
	"""
	merchant		= models.ForeignKey(Merchant, related_name="featured")

	time_stamp		= models.DateField()
	description		= models.TextField()

	def __unicode__(self):
		return self.merchant.name
	

class Offer(logicaldelete.models.Model):		
	merchant		= models.ForeignKey(Merchant, related_name="offers_published")
	title 			= models.CharField(max_length=128, blank=True, help_text="Sexy offer headline. Keep it under 100 characters.")
	description		= models.TextField(blank=True)
	percentage		= models.IntegerField(verbose_name="Percent off (%)", default=0)
	dollar_off		= models.FloatField(verbose_name="Dollar off ($)", default=0)
	offer_value			= models.FloatField(verbose_name="Offer Value ($)", default =0)	
	time_stamp		= models.DateTimeField()
	starting_time	= models.DateTimeField(blank=True, null=True)
	duration		= models.IntegerField(default=90)
	max_offers		= models.IntegerField(verbose_name="Max # of customers", default=50, help_text="Maximum number of customers you want to send to")
	num_init_sentto		= models.IntegerField(default=0) # number of customers the offer was sent to
	num_resent_to		= models.IntegerField(default=0) # number of customers the offer was resent to
	is_merchant_txted	= models.BooleanField(default=False) # True if the merchant was informed the status of the offer after it's expired
	img				= ImageField(upload_to='offers/', blank=True)

	expired = models.BooleanField(default=False)
	expired_time = models.DateTimeField(null=True, blank=True)
	redistributable = models.BooleanField(default=True)
	is_processing = models.BooleanField(default=True)
	redistribute_processing = models.BooleanField(default=False)
	#locations = models.ManyToManyField(Location)

	location_created = models.ForeignKey(Location, null=True, blank=True)

	starter_phone = models.ForeignKey(MerchantPhone, null =True)

	def __unicode__(self):
		return self.title

	def update_expired_codes(self):
	
		for oc in self.offercode_set.all():
			oc.code = oc.code + self.trackingcode.code
			oc.save()
	
	def expire(self, reset_duration=False):
		"""
			expire the offer
		"""
		#self.expired = True
		if reset_duration:
			# shorten duration manually
			self.duration = 0	
		self.save() 

	def is_active(self):
	#	print "description: ",self.description
		if self.expired_time:
			active = self.expired_time > datetime.now()
		else:
			active = self.starting_time+timedelta(minutes=self.duration) > datetime.now()
		if not active:
			self.expire()
		return active

	def num_forwarded(self):
		return self.offercode_set.count()-self.num_init_sentto-self.num_resent_to

	def num_direct_received(self):
		return self.num_init_sentto+self.num_resent_to

	def num_redeemed(self):
		return self.offercode_set.filter(redeem_time__isnull=False).count()

	def num_received(self):
		return self.offercode_set.count()
	
	def set_location_from_latlon(self, lat , lon):
		self.created_location = Location.objects.create(location=(fromstr("POINT(%s %s)" % (lon, lat))))
		self.save()

	def offer_detail(self, past=False):
		"""
			Used to report to merchant mobile phone
		"""
		data = {}

		data["offer_id"] = self.id
		data["title"] = self.title
		data["description"] = self.description
		
		if self.dollar_off != 0:
		    data["amount"] = self.dollar_off
		    data["unit"] = 1
		elif self.percentage != 0:
		    data["amount"] = self.percentage
		    data["unit"] = 2
		
		data["duration"] = self.duration
		
		expire_time = self.starting_time + timedelta(minutes=self.duration)
		data["expires"] = int(time.mktime(expire_time.timetuple())) #pretty_date(expire_time-datetime.now())

		# currently received does not account for forwarded code
		#data["total_received"] = self.num_received()
		recvd = self.num_direct_received()
		data["received"] = recvd 
		redeemed = self.num_redeemed()
		data["redeemed"] = self.num_redeemed() 
		if recvd == 0:
			data["redeem_rate"] = 0
		else:
			data["redeem_rate"] = redeemed/float(recvd)*100

		data["img"] = self.get_image()

		if not past:
			data["redistributable"] = self.redistributable
			data["is_processing"] = self.is_processing
			data["redistribute_processing"] = self.redistribute_processing

		return data
		
	def customer_offer_detail(self, user):
		"""
			Used to report to customer mobile phone
		"""
		location = self.merchant.location.location
		
		offer_detail = {
			"offer_id": self.id,
			"name": self.title,
			"merchant_name": self.merchant.business_name,
			"description": self.description,
			# expires for older version only
			"expires": pretty_date(self.expired_time - datetime.now()),
			"expires_time": int(time.mktime(self.expired_time.timetuple())),
			"phone": self.merchant.phone,
			"address1": self.merchant.address_1,
			"citystatezip": self.merchant.zipcode.citystate(),
			"lat": location.y,
			"lon": location.x,
			"img": self.get_image(),
			"banner": self.merchant.get_banner(),
		}
		if self.percentage:
			offer_detail["percentage"] = self.percentage
		elif self.dollar_off:
			offer_detail["dollar_off"] = self.dollar_off
		
		try:
			offercode = OfferCode.objects.get(offer=self, customer=user)
			offer_detail["offer_code_id"] = offercode.id
			offer_detail["code"] = offercode.code
			if offercode.forwarder:
				offer_detail["forwarder"] = str(offercode.forwarder)
		except OfferCode.DoesNotExist:
			pass

		return offer_detail

	def get_image(self):
		if self.img:
			return self.img.url
		else:
			return settings.DEFAULT_OFFER_IMG_URL	

	def gen_tracking_code(self):
		track_code = gen_tracking_code()
		while TrackingCode.objects.filter(code__iexact=track_code):
			track_code = gen_tracking_code()
		TrackingCode.objects.create(
			offer=self,
			code = track_code
		)
		return track_code

	def gen_offer_code(self, customer, rtype = 1):
		if self.offercode_set.filter(customer=customer).exists():
			return
		gen_code = gen_offer_code().lower()
		while self.offercode_set.filter(code__iexact=gen_code):
			gen_code = gen_offer_code()
		
		if rtype != 4 and self.redistribute_processing == True:
			rtype = 2
		
		self.offercode_set.create (
			customer=customer,
			code=gen_code,
			time_stamp=self.time_stamp,
			expiration_time=self.starting_time+timedelta(minutes=self.duration),
			rtype = rtype,
		)

	
	def gen_offer_codes(self, customers):
		"""
			TODO: this part needs to be optimized so that the offer code generation
				does not have a bottle neck
		"""
		count=0
		for customer in customers:
			if customer.is_taking_offers():
				if self.offercode_set.filter(customer = customer).exists():
					continue
				self.gen_offer_code(customer)
				count = count +1
				#print count, customer
				customer.update_offer_count()
		#print "reached " , count
		return count


	def gen_forward_offercode(self,original_code,phone):
	
		#forwarder = OfferCode.objects.filter(code__iexact=original_code)
		
		gen_code = gen_offer_code()
		phone =parse_phone_number(phone)
	
		while (OfferCode.objects.filter(code__iexact=gen_code).count()>0):
			gen_code = gen_offer_code()
		forwarder=original_code.customer
	
		#friend = Customer.objects.get(phone=(phone))
		print phone
		if CustomerPhone.objects.filter(number=phone).exists():
			p = CustomerPhone.objects.get(number=phone)
			#if p.shoppleyuser.is_customer():
			friend = p.customer
			o=self.offercode_set.create(
					customer=friend,
					code = gen_code,
					forwarder=forwarder,
					time_stamp=datetime.now(),
					expiration_time=original_code.expiration_time,
					rtype = 3)
			o.save()
			forwarder.customer_friends.add(p.customer)
			return o, None # for existing customer

#		except Customer.DoesNotExist:
			# TODO: Need to replace the following with code below
			# create a customer
			# create a username with phone num and create random password

			#print "Creating NEW user with username:", phone
		u, created = User.objects.get_or_create(username=phone)
		u.email=""
		s = string.letters+string.digits
		rand_passwd = ''.join(random.sample(s,6))
		u.set_password(rand_passwd)	
		u.save()
		
		friend, created = Customer.objects.get_or_create(user=u, address_1="", address_2="", zipcode=original_code.customer.zipcode)
		p= CustomerPhone.objects.create(number = phone, customer = friend)
		if created:
			friend.set_location_from_address()	
		# send out a new offercode
		o=self.offercode_set.create(
				customer = friend,
				code = gen_code,
				forwarder=forwarder,
				time_stamp=datetime.now(),
				expiration_time=original_code.expiration_time,
				rtype = 3)
		o.save()
			
		forwarder.customer_friends.add(friend)
		return o, rand_passwd  # for new customer

	
	def redistribute(self):
		"""
			checks if offer is redistributable and sets flags to queue for
			redistribution and return True

			if not redistributable then return False 
		"""
		if self.redistributable:
			self.redistribute_processing = True
			self.redistributable = False
			self.save()
			return True

		else:
			return False


	def redeemers(self):
		"""
			return list of redeemers
		"""
		return self.offercode_set.filter(redeem_time__isnull=False)

shoppley.com/shoppley/apps/offer/templates/offer/admin_start_offer.html
{% extends "offer/offer_base.html" %}
{% load i18n %}


{% load uni_form_tags %}
{% block head_title %}{% trans "Shoppley" %}{% endblock %}




{% block body %}

	  
<div class="form">

	<div class="span-17">
		<p> Starting an offer for</p>
		<h3>{{ business_name }}</h3>
		<p>{{ address }}</p>
        	<form class="admin-offer-start-form" id="admin_offer_start_form" method="post" action="{% url admin_start_offer  id %}" >{% csrf_token %}

			<fieldset class="inlineLabels">
                                        {{ form|as_uni_form }}
                                        <div class="form_blick">
                                                <input type="submit" value="{% trans "Start Offer &raquo;" %}" />
                                        </div>
                        </fieldset>

		</form>
	</div>

</div>

<div class="clear" style="height: 40px;">&nbsp;</div>

        <div class="clear">&nbsp;</div>


{% endblock %}
{% block extra_scripts %}

                <style type="text/css">
                        .formHint {
                                display:none;
                        }
                </style>
        <script type="text/javascript">
                $(function() {
                 $('id_date').datepicker({minDate:0});
                 $('#id_title').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
                 $('#id_value').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
                 $('#id_description').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
                 $('#id_max_offers').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
                 $('#id_discount_1').tipsy({html: true, trigger: 'focus', gravity: 'w', fallback: 'For FREE offers select custom option'});
                 $('#id_duration').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
                });
                 $('#id_title').counter();
                 var is_now = false;
                 $('#id_now').click(function(){
                        if (is_now) {
                                $('#div_id_date').fadeIn(600);
                                $('#div_id_time').fadeIn(600);
                                is_now = false;
                        }
                        else {
                                $('#div_id_date').fadeOut(600);
                                $('#div_id_time').fadeOut(600);
                                is_now = true;
                        }
                 });
        </script>


{% endblock %}

shoppley.com/shoppley/apps/offer/templates/offer/customer_home.html
{% extends "site_base.html" %}

{% load i18n %}
{% load uni_form_tags %}

{% block head_title %}{% trans "My Offers" %}{% endblock %}

{% block body %}

	<h1>{% trans "My Offers" %}</h1>

	<div class="customer-incentive-explanation">
	Every time you redeem an offer you will receive <b>5 points</b>.<br> 
	Future: Merchants will announce offers redeemable with points.<br>
	</div>

	<hr class="space">

	<div class="top-dash span-24 last">
		<div class="left-dash span-12">
			<div class="heading ui-widget-header span-12 last">
				Received Offers
			</div>
			<div class="ui-widget-content offers-min-height span-12 last">
			  {% for o in offers_received %}
			  <div class="item span-12 last">
				<div class="span-3">
				  {{ o.offer.merchant.business_name }}
				</div>
				<div class="span-3">
				  {{ o.offer.name }}
				</div>
				<div class="span-3">
				  {{ o.offer.description }}
				</div>
				<div class="span-3 last">
				  {{ o.expiration_time|date:"M d, y f A" }}
				</div>
			  </div>
			  {% endfor %}
			</div>
		</div>

		<div class="right-dash span-12 last">
			<div class="heading ui-widget-header span-12 last">
				Redeemed Offers
			</div>
			<div class="ui-widget-content offers-min-height span-12 last">
			  {% for o in offers_redeemed %}
			  <div class="item span-12 last">
				<div class="span-3">
				  {{ o.offer.merchant.business_name }}
				</div>
				<div class="span-3">
				  {{ o.offer.name }}
				</div>
				<div class="span-3">
				  {{ o.offer.description }}
				</div>
				<div class="span-3 last">
				  {{ o.redeem_time }}
				</div>
			  </div>
			  {% endfor %}
			</div>
		</div>
	</div> <!-- top-dash -->

	<hr class="space">

	<div class="bottom-dash span-24 last">
		<div class="left-dash span-12">
			<div class="heading ui-widget-header span-12 last">
				Featured: Would you like to add to your offers?	
			</div>
			<div class="features ui-widget-content offers-min-height span-12 last">
				{% for f in featured %}
				  {% if forloop.first %}
					<div class="span-12 last">
					  <div class="span-4">
						Image
					  </div>
					  <div class="span-8 last">
						<div class="merchant-name span-8 last">
						  {{ f.merchant.business_name }}
						</div>
						<div class="merchant-highlight span-8 last">
						  {{ f.description }}
						</div>
					  </div>
					</div>
				  {% else %}
					<div class="span-12 last">
					  <div class="span-4">
						Small Image
					  </div>
					  <div class="merchant-name span-8 last">
						{{ f.merchant.business_name }}
					  </div>
					</div>
				  {% endif %}
				{% endfor %}
			</div>

		</div>

		<div class="right-dash span-12 last">
			<div class="heading ui-widget-header span-12 last">
				Link your credit card for more personalized offers
			</div>
			<div class="buxfer-form ui-widget-content offers-min-height span-12 last">
			  <div class="sub-comment">Receive 50 points when you link Buxfer account.</div>
			  <hr class="space">	
			  <form class="linkbuxfer uniForm" id="linkbuxfer-form" method="post" action="{% url link_buxfer %}">

				<fieldset class="inlineLabels">
				  {{ buxfer_form|as_uni_form }}
				</fieldset>
				<div class="form_blick push-8">
					<input type="submit" value="{% trans "Link Buxfer &raquo;" %}" />
				</div>
			  </form>

			</div>
		</div>


	</div> <!-- bottom-dash -->


	

{% endblock %}

shoppley.com/shoppley/apps/offer/templates/offer/customer_offer_home.html
{% extends "offer/offer_base.html" %}

{% load i18n %}
{% load uni_form_tags %}
{% load offer_tags %}
{% block head_title %}{% trans "Shoppley" %}{% endblock %}

{% block body %}

        <div class="span-17">
        <div class="customer-stats-box stats-box main-box">
					<h3>Your offer summary for past <strong>7</strong> days</h3>
						<div class="customer-stats stats">
							<span class="used-count">18</span>{% trans " redeemed " %}
							<span class="expired-count">44</span>{% trans " expired " %}
							<span class="recvd-count">16</span>{% trans " received " %}
						<span class="total-pt">60</span>{% trans " pt total" %} 
						</div>
				 </div>
			<div class="clear">&nbsp;</div>			
			<div class="current-offers-box">
				{% if other_active_offers.object_list %}
					
					{% for offer in other_active_offers.object_list %}
						 
						{% customer_offer_tag offer %}
					{% endfor %}
				{% endif %}

				
				<div class="pagination">
				    <span class="step-links">
				        {% if other_active_offers.has_previous %}
				            <a href="?page={{ other_active_offers.previous_page_number }}">previous</a>
				        {% endif %}

				        <span class="current">
				            Page {{ other_active_offers.number }} of {{ other_active_offers.paginator.num_pages }}.
				        </span>

				        {% if other_active_offers.has_next %}
				            <a href="?page={{ other_active_offers.next_page_number }}">next</a>
				        {% endif %}
				    </span>
				</div>
			</div>
       </div>
	

        <div class="span-7 last">
                        <div class="offer-settings main-box">
                                <h3>{% trans "My offer settings" %}</h3>
				<p>{% trans "daily  weekly" %}</p>

                        </div>
			<div class="clear">&nbsp;</div>
			<div class="used-offers-box main-box">
				<h3>{% trans "Used offer summary" %}</h3>
				{% if used_offercodes %}


					{% for offercode in used_offercodes %}
						{% customer_offercode_side_tag offercode %}
					{% endfor %}
				{% endif %}
			</div>

        </div>

        <div class="clear" style="height: 40px;">&nbsp;</div>

	<div class="clear">&nbsp;</div>

{% endblock %}
{% block extra_scripts %}



        <script type="text/javascript">
	
                $(function() {




                });
        </script>
{% endblock %}

shoppley.com/shoppley/apps/offer/templates/offer/merchant_offer_start.html
{% extends "offer/offer_base.html" %}
{% load i18n %}


{% load uni_form_tags %}
{% block head_title %}{% trans "Shoppley" %}{% endblock %}




{% block body %}
<div class="offer-form">
	
		<h3>Start an offer now!</h3>
        	<form class="offer-start-form uniform" id="offer_start_form" method="post" action="{% url merchant_start_offer %}" >{% csrf_token %}

			<fieldset class="inlineLabels">
                                        {{ form|as_uni_form }}
                                        <div class="form_blick">
                                                <input type="submit" value="{% trans "Start Offer &raquo;" %}" />
						<!--a class="shoppley-btn"><input type="submit" value="{% trans "Start offer &raquo;" %}"/></a-->
                                        </div>
                        </fieldset>
		</form>
	</div>

 <div class="clear" style="height: 40px;">&nbsp;</div>

        <div class="clear">&nbsp;</div>


{% endblock %}
{% block extra_scripts %}

		<style type="text/css">
			.formHint {
				display:none;
			}
		</style>
        <script type="text/javascript">
		$(function() {
		 $('id_date').datepicker({minDate:0});
		 $('#id_title').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
		 $('#id_value').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
		 $('#id_description').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
		 $('#id_max_offers').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
		 $('#id_discount_1').tipsy({html: true, trigger: 'focus', gravity: 'w', fallback: 'For FREE offers select custom option'});
		 $('#id_duration').tipsy({html: true, trigger: 'focus', gravity: 'w', title: function() { return $(this).parent().children("p").html(); }});
		});
		 $('#id_title').counter();
		 var is_now = false;
		 $('#id_now').click(function(){
			if (is_now) {
				$('#div_id_date').fadeIn(600);
				$('#div_id_time').fadeIn(600);
				is_now = false;
			}
			else {
				$('#div_id_date').fadeOut(600);
				$('#div_id_time').fadeOut(600);
				is_now = true;
			}
		 });
        </script>

{% endblock %}

shoppley.com/shoppley/apps/offer/templates/offer/offer_home.html
Hi! This is offer